import React, { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import api from "../utils/api";
import { jsPDF } from "jspdf";
import { VerifyQRCode } from "../utils/qrHelper";

export default function Verify() {
  const [searchParams] = useSearchParams();
  const [certId, setCertId] = useState(searchParams.get("id") || "");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [letterLoading, setLetterLoading] = useState(false);
  const issueDate = useMemo(
    () => (result?.data?.completionDate ? new Date(result.data.completionDate).toLocaleDateString("en-IN") : ""),
    [result]
  );

  const verifyCertificate = async (targetId = certId) => {
    if (!targetId) return;
    try {
      setLoading(true);
      const response = await api.get(`/certificates/verify/${targetId}`);
      setResult(response.data);
    } catch (error) {
      setResult(error.response?.data || { valid: false, reason: "not_found" });
    } finally {
      setLoading(false);
    }
  };

  const downloadVerificationLetter = async () => {
    if (!result?.valid) return;
    try {
      setLetterLoading(true);
      const response = await api.get(`/certificates/verification-letter/${result.data.certId}`);
      const { certificate, letterId, issuedAt, statement, organization, signedBy, supportEmail } = response.data;
      const doc = new jsPDF();
      doc.setFillColor(10, 22, 40);
      doc.rect(0, 0, 210, 32, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.text(`${organization} Verification Letter`, 20, 21);
      doc.setTextColor(32, 41, 57);
      doc.setDrawColor(245, 158, 11);
      doc.setLineWidth(0.8);
      doc.roundedRect(14, 40, 182, 88, 4, 4);
      doc.setFontSize(11);
      doc.text(`Letter ID: ${letterId}`, 22, 52);
      doc.text(`Issued At: ${new Date(issuedAt).toLocaleString("en-IN")}`, 22, 60);
      doc.text(`Certificate ID: ${certificate.certId}`, 22, 72);
      doc.text(`Student Name: ${certificate.studentName}`, 22, 80);
      doc.text(`Course Name: ${certificate.courseName}`, 22, 88);
      doc.text(`College: ${certificate.college}`, 22, 96);
      doc.text(`Duration: ${certificate.duration}`, 22, 104);
      doc.text(`Completion Date: ${new Date(certificate.completionDate).toLocaleDateString("en-IN")}`, 22, 112);
      doc.setFontSize(12);
      doc.text(statement, 20, 145, { maxWidth: 170 });
      doc.setFontSize(10);
      doc.text("This verification letter is system-generated by InternTech records.", 20, 166);
      doc.text(`Signed by: ${signedBy}`, 20, 173);
      doc.text(`For recruiter support, write to ${supportEmail}.`, 20, 180);
      doc.save(`${certificate.certId}-verification-letter.pdf`);
    } finally {
      setLetterLoading(false);
    }
  };

  useEffect(() => {
    if (searchParams.get("id")) {
      verifyCertificate(searchParams.get("id"));
    }
  }, [searchParams]);

  return (
    <div className="bg-[radial-gradient(circle_at_top,_rgba(37,99,235,0.14),_transparent_45%),linear-gradient(180deg,#f8fbff_0%,#ffffff_52%,#f7f4ee_100%)] px-4 py-16 dark:bg-slate-950">
      <div className="mx-auto max-w-5xl">
        <div className="rounded-[40px] border border-slate-200 bg-white/95 p-8 shadow-[0_28px_80px_rgba(15,23,42,0.08)] backdrop-blur dark:border-slate-800 dark:bg-slate-900/95">
          <div className="grid gap-8 lg:grid-cols-[1fr_340px]">
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.28em] text-blue">Certificate Verification</p>
              <h1 className="mt-3 text-4xl font-bold text-slate-950 dark:text-white">Verify an InternTech certificate</h1>
              <p className="mt-4 max-w-2xl text-sm leading-7 text-slate-600 dark:text-slate-300">
                Enter a certificate ID to confirm its authenticity, inspect learner details, and download a recruiter-ready verification letter.
              </p>
              <div className="mt-8 flex flex-col gap-3 sm:flex-row">
                <input value={certId} onChange={(event) => setCertId(event.target.value)} placeholder="Enter certificate ID" className="flex-1 rounded-2xl border border-slate-200 px-4 py-4 outline-none focus:border-blue dark:border-slate-700 dark:bg-slate-950" />
                <button type="button" onClick={() => verifyCertificate()} className="rounded-2xl bg-blue px-6 py-4 text-sm font-semibold text-white transition hover:bg-navy">
                  {loading ? "Verifying..." : "Verify Now"}
                </button>
              </div>
            </div>
            <div className="rounded-[32px] border border-gold/40 bg-[linear-gradient(180deg,#fffdf7_0%,#fbf3de_100%)] p-6 text-slate-900 shadow-[inset_0_0_0_1px_rgba(245,158,11,0.18)]">
              <p className="text-xs font-semibold uppercase tracking-[0.28em] text-slate-500">Official Trust Panel</p>
              <h2 className="mt-3 text-2xl font-bold text-navy">Recruiter-friendly verification</h2>
              <div className="mt-5 space-y-3 text-sm text-slate-600">
                <p>Instant status check against InternTech records.</p>
                <p>Verification letter PDF for college and recruiter workflows.</p>
                <p>QR-backed verification route for easy cross-checking.</p>
              </div>
            </div>
          </div>

          {result ? (
            <div className={`mt-8 rounded-[32px] border p-6 ${result.valid ? "border-success/30 bg-success/10" : "border-danger/30 bg-danger/10"}`}>
              {result.valid ? (
                <div className="grid gap-6 lg:grid-cols-[1.25fr_300px]">
                  <div>
                    <div className="inline-flex rounded-full bg-success px-4 py-2 text-xs font-bold uppercase tracking-[0.24em] text-white">
                      Verified
                    </div>
                    <h2 className="mt-4 text-3xl font-bold text-slate-950 dark:text-white">{result.data.studentName}</h2>
                    <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">
                      This certificate is authentic, active, and matches the official InternTech verification database.
                    </p>
                    <div className="mt-6 grid gap-3 text-sm text-slate-700 dark:text-slate-200 sm:grid-cols-2">
                      <p><span className="font-semibold">Course:</span> {result.data.courseName}</p>
                      <p><span className="font-semibold">College:</span> {result.data.college}</p>
                      <p><span className="font-semibold">Certificate ID:</span> {result.data.certId}</p>
                      <p><span className="font-semibold">Duration:</span> {result.data.duration}</p>
                      <p><span className="font-semibold">Issue Date:</span> {issueDate}</p>
                      <p><span className="font-semibold">Status:</span> Active and verifiable</p>
                    </div>
                    <button type="button" onClick={downloadVerificationLetter} className="mt-6 rounded-2xl bg-blue px-5 py-3 text-sm font-semibold text-white transition hover:bg-navy">
                      {letterLoading ? "Preparing Letter..." : "Download Verification Letter PDF"}
                    </button>
                  </div>
                  <div className="rounded-[28px] border border-slate-200 bg-white p-5 text-center shadow-sm dark:border-slate-800 dark:bg-slate-950">
                    <p className="text-xs font-semibold uppercase tracking-[0.28em] text-slate-500">Scan To Verify</p>
                    <div className="mt-4 flex justify-center">
                      <div className="rounded-2xl bg-white p-3 shadow-sm dark:bg-slate-900">
                        <VerifyQRCode certId={result.data.certId} size={120} />
                      </div>
                    </div>
                    <p className="mt-4 text-sm font-semibold text-slate-700 dark:text-slate-200">Authentic and issued by InternTech</p>
                    <p className="mt-2 text-xs leading-6 text-slate-500 dark:text-slate-400">
                      Recruiters and institutions can use this code or the certificate ID to validate the learner record.
                    </p>
                  </div>
                </div>
              ) : (
                <>
                  <p className="text-lg font-bold text-danger">{result.reason === "revoked" ? "CERTIFICATE REVOKED" : "INVALID CERTIFICATE ID"}</p>
                  <p className="mt-3 text-sm text-slate-700 dark:text-slate-200">
                    {result.reason === "revoked"
                      ? result.revokeReason || "This certificate has been revoked."
                      : "This certificate does not exist in our records."}
                  </p>
                </>
              )}
            </div>
          ) : null}
        </div>
      </div>
    </div>
  );
}
